### ISSUE TITLE
Make an output folder BIDS compatible in derivatives/

### ISSUE THREAD

**Issue by julfou81** [Macatools/macapype#116]
I wonder if we should not create and output folder where all the useful images will be: brain mask, segmentation tissue probability images, surfaces ... It is cumbersome to navigate through all the directories created by nipype. It is ok for debugging, not for production. If I take the example of fmriprep, which paves the way, the nipype outputs go into a temporary folder and the usable output is saved in the derivatives/fmriprep folder of the project.

**Comment by SylvainTakerkart** [comment]
In this direction: maybe it might even be better that macapype works with a BIDS input, and writes in a BIDS derivative folder within the existing BIDS directory... In short, that would mean that macapype is now a BIDSApp, which would be great both for promoting the use of macapype, and also for its ease of use for the users...

WDYT?
