### ISSUE TITLE
wrap NMT v2 when available

### ISSUE THREAD

**Issue by davidmeunier79** [Macatools/macapype#118]
https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/nonhuman/macaque_tempatl/template_nmtv2.html#nh-macaque-template-nmtv2

Download:
wget https://afni.nimh.nih.gov/pub/dist/atlases/macaque/nmt/NMT_v2.0_sym.tgz
tar -xvf NMT_v2.0_sym.tgz

**Comment by kepkeeloh** [comment]
Related to this issue, there is a new 5-tissue segmentation mask that comes with the NMTv2. 

We will need to adjust the AtroposN4 node to incorporate this 5-tissue segmentation, and also to output 5 different outputs instead of 3 previously.
