### ISSUE TITLE
Integration of the JunaChimp Template and DaVi parcellation for chimpanzee images processing

### ISSUE THREAD

**Issue by FeHoff** [Macatools/macapype#126]
Integrate the JunaChimp Template and DaVi parcellation for chimpanzee mapping and cross species comparison into mamapype

**Comment by kepkeeloh** [comment]
Hi @FeHoff, some more precise steps for building the pipeline:

1) Decide on which macapype pipeline to use (spm vs ants, whether a T2w image is available)

2) Decide on the optimal parameters to run your choice of pipeline, and create a "params.json" and "indiv_params.json" file specific for your chimpanzee data which basically "tweaks" the processing steps for your data.. I would suggest you can just start by editing directly from one of the existing jsons to have an idea of what parameters are tweakable. 

3) we might have some fine-tuning to do to find the best set of parameters (e.g. for brain extraction) that work best for one chimp from your database, and once that is done, we can sit back and apply the same for all the rest of the chimps :)
