### ISSUE TITLE
add pybids without session (no ses- in directory structure and file names)

### ISSUE THREAD

**Issue by davidmeunier79** [Macatools/macapype#212]
As suggested by @FeHoff

**Comment by FeHoff** [comment]
If implemented I'll directly test it. Thanks!

**Comment by davidmeunier79** [comment]
Hi @FeHoff would you point me a dataset from PRIME-DE where the session is missing in the BIDS data structure, so I can make some tests? Many thanks

**Comment by FeHoff** [comment]
The huge sample from [University of Wisconsin–Madison](http://fcon_1000.projects.nitrc.org/indi/PRIME/uwmadison.html) has no session:
prime_de/bids/uwmadison/anat
                                                  dwi
                                                  fmap
                                                  func

**Comment by davidmeunier79** [comment]
thanks I will have a look and let you know

**Comment by davidmeunier79** [comment]
Solved in https://github.com/Macatools/macapype/pull/216 @FeHoff 
Will be made available in next release (v0.3.3)
