### ISSUE TITLE
Freesurfer space discussion 

### ISSUE THREAD

**Issue by ostanley** [Macatools/macapype#96]
Re: our meeting I am putting this here so it is in a central place. There are two reasons that freesurfer and macapype may not play nice together. 

There are two freesurfer issues where it changes data in disadvantageous ways: 
1) run with the tag `-hires` or it will always resample to 1m iso. That is a recon-all tag so it is not in all binaries but most. 
2) freesurfer puts things in its freesurfer space (which leaves them in RAS in other viewers like itksnap). 
For surfaces the command `mris_convert` with the -`-to-scanner` flag will apply the correct transform to fix this.
For volumes it is the transform given by `mri_info --vox2ras-tkr orig.mgz` I think but I am less sure.

**Comment by davidmeunier79** [comment]
This issue was dealt with when adding the nii_to_fs_mesh pipe in PR https://github.com/Macatools/macapype/issues/112
